2017-03-15 15:45:19,627 [MainThread:140146814478080] [app_info:96] [tasks:judge] [ERROR]- HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /vjudge/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7672906b10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-03-15 15:48:15,752 [MainThread:140146814478080] [app_info:96] [tasks:judge] [ERROR]- HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /vjudge/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f76728f7d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-03-15 15:50:13,854 [MainThread:140146814478080] [app_info:96] [tasks:judge] [ERROR]- HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /vjudge/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f76728cc250>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-03-15 21:14:37,045 [MainThread:140341740394240] [app_info:96] [tasks:judge] [ERROR]- HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /vjudge/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa3d50dec50>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-04-04 16:35:48,297 [MainThread:140671138584320] [app_info:96] [tasks:judge] [ERROR]- HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /vjudge/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff0891af650>: Failed to establish a new connection: [Errno 111] Connection refused',))
